#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x687393EE37D128F8 (matthieu@herrb.eu)
#
Name     : libXrender
Version  : 0.9.10
Release  : 15
URL      : http://xorg.freedesktop.org/releases/individual/lib/libXrender-0.9.10.tar.bz2
Source0  : http://xorg.freedesktop.org/releases/individual/lib/libXrender-0.9.10.tar.bz2
Source99 : http://xorg.freedesktop.org/releases/individual/lib/libXrender-0.9.10.tar.bz2.sig
Summary  : X Render Library
Group    : Development/Tools
License  : HPND
Requires: libXrender-lib
Requires: libXrender-doc
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : pkgconfig(32renderproto)
BuildRequires : pkgconfig(32x11)
BuildRequires : pkgconfig(32xorg-macros)
BuildRequires : pkgconfig(renderproto)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xorg-macros)

%description
libXrender - library for the Render Extension to the X11 protocol
All questions regarding this software should be directed at the
Xorg mailing list:

%package dev
Summary: dev components for the libXrender package.
Group: Development
Requires: libXrender-lib
Provides: libXrender-devel

%description dev
dev components for the libXrender package.


%package dev32
Summary: dev32 components for the libXrender package.
Group: Default
Requires: libXrender-lib32
Requires: libXrender-dev

%description dev32
dev32 components for the libXrender package.


%package doc
Summary: doc components for the libXrender package.
Group: Documentation

%description doc
doc components for the libXrender package.


%package lib
Summary: lib components for the libXrender package.
Group: Libraries

%description lib
lib components for the libXrender package.


%package lib32
Summary: lib32 components for the libXrender package.
Group: Default

%description lib32
lib32 components for the libXrender package.


%prep
%setup -q -n libXrender-0.9.10
pushd ..
cp -a libXrender-0.9.10 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1500992595
export CFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export FFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
%configure --disable-static
make V=1  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make V=1  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1500992595
rm -rf %{buildroot}
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/Xrender.h
/usr/lib64/libXrender.so
/usr/lib64/pkgconfig/xrender.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libXrender.so
/usr/lib32/pkgconfig/32xrender.pc
/usr/lib32/pkgconfig/xrender.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/libXrender/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libXrender.so.1
/usr/lib64/libXrender.so.1.3.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libXrender.so.1
/usr/lib32/libXrender.so.1.3.0
