#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libXrender
Version  : 0.9.10
Release  : 9
URL      : http://xorg.freedesktop.org/releases/individual/lib/libXrender-0.9.10.tar.bz2
Source0  : http://xorg.freedesktop.org/releases/individual/lib/libXrender-0.9.10.tar.bz2
Summary  : X Render Library
Group    : Development/Tools
License  : HPND
Requires: libXrender-lib
Requires: libXrender-doc
BuildRequires : pkgconfig(renderproto)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xorg-macros)

%description
libXrender - library for the Render Extension to the X11 protocol
All questions regarding this software should be directed at the
Xorg mailing list:

%package dev
Summary: dev components for the libXrender package.
Group: Development
Requires: libXrender-lib
Provides: libXrender-devel

%description dev
dev components for the libXrender package.


%package doc
Summary: doc components for the libXrender package.
Group: Documentation

%description doc
doc components for the libXrender package.


%package lib
Summary: lib components for the libXrender package.
Group: Libraries

%description lib
lib components for the libXrender package.


%prep
%setup -q -n libXrender-0.9.10

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/Xrender.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/libXrender/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
